"""create classification events table

Revision ID: 725f8e5aa178
Revises: fe92afbedd02
Create Date: 2026-06-25 18:46:52.476797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '725f8e5aa178'
down_revision: Union[str, Sequence[str], None] = 'fe92afbedd02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('predicted_label', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('classification_status', sa.String(length=32), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('top_predictions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topic_match_status', sa.String(length=32), nullable=False),
    sa.Column('topic_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_action', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_events_classification_status'), 'classification_events', ['classification_status'], unique=False)
    op.create_index(op.f('ix_classification_events_created_at'), 'classification_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_classification_events_event_id'), 'classification_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_classification_events_id'), 'classification_events', ['id'], unique=False)
    op.create_index(op.f('ix_classification_events_predicted_label'), 'classification_events', ['predicted_label'], unique=False)
    op.create_index(op.f('ix_classification_events_recommended_action'), 'classification_events', ['recommended_action'], unique=False)
    op.create_index(op.f('ix_classification_events_topic_match_status'), 'classification_events', ['topic_match_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classification_events_topic_match_status'), table_name='classification_events')
    op.drop_index(op.f('ix_classification_events_recommended_action'), table_name='classification_events')
    op.drop_index(op.f('ix_classification_events_predicted_label'), table_name='classification_events')
    op.drop_index(op.f('ix_classification_events_id'), table_name='classification_events')
    op.drop_index(op.f('ix_classification_events_event_id'), table_name='classification_events')
    op.drop_index(op.f('ix_classification_events_created_at'), table_name='classification_events')
    op.drop_index(op.f('ix_classification_events_classification_status'), table_name='classification_events')
    op.drop_table('classification_events')
    # ### end Alembic commands ###
