"""create uncertain classifications table

Revision ID: 770ee153e28c
Revises: a27f7ff8c685
Create Date: 2026-06-25 12:04:21.856237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '770ee153e28c'
down_revision: Union[str, Sequence[str], None] = 'a27f7ff8c685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uncertain_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('predicted_label', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('top_predictions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('assigned_label', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uncertain_classifications_created_at'), 'uncertain_classifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_uncertain_classifications_event_id'), 'uncertain_classifications', ['event_id'], unique=True)
    op.create_index(op.f('ix_uncertain_classifications_id'), 'uncertain_classifications', ['id'], unique=False)
    op.create_index(op.f('ix_uncertain_classifications_predicted_label'), 'uncertain_classifications', ['predicted_label'], unique=False)
    op.create_index(op.f('ix_uncertain_classifications_review_status'), 'uncertain_classifications', ['review_status'], unique=False)
    op.drop_index(op.f('ix_complaints_embedding_hnsw'), table_name='complaints', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw', postgresql_where='(embedding IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_complaints_embedding_hnsw'), 'complaints', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw', postgresql_where='(embedding IS NOT NULL)')
    op.drop_index(op.f('ix_uncertain_classifications_review_status'), table_name='uncertain_classifications')
    op.drop_index(op.f('ix_uncertain_classifications_predicted_label'), table_name='uncertain_classifications')
    op.drop_index(op.f('ix_uncertain_classifications_id'), table_name='uncertain_classifications')
    op.drop_index(op.f('ix_uncertain_classifications_event_id'), table_name='uncertain_classifications')
    op.drop_index(op.f('ix_uncertain_classifications_created_at'), table_name='uncertain_classifications')
    op.drop_table('uncertain_classifications')
    # ### end Alembic commands ###
