"""create complaints table

Revision ID: af4208c3615d
Revises: fb5fd1b1b99f
Create Date: 2026-06-25 11:04:59.598845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4208c3615d'
down_revision: Union[str, Sequence[str], None] = 'fb5fd1b1b99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.BigInteger(), nullable=False),
    sa.Column('date_received', sa.DateTime(timezone=True), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('issue', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('submitted_via', sa.String(length=64), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_company'), 'complaints', ['company'], unique=False)
    op.create_index(op.f('ix_complaints_complaint_id'), 'complaints', ['complaint_id'], unique=True)
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_issue'), 'complaints', ['issue'], unique=False)
    op.create_index(op.f('ix_complaints_product'), 'complaints', ['product'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_product'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_issue'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_company'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
