"""add csi fields to complaints

Revision ID: caf58829c37b
Revises: 9fdaa002a54b
Create Date: 2026-06-25 20:00:09.084235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf58829c37b'
down_revision: Union[str, Sequence[str], None] = '9fdaa002a54b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('csi_score', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('sentiment', sa.String(length=32), nullable=True))
    op.add_column('complaints', sa.Column('severity', sa.String(length=32), nullable=True))
    op.add_column('complaints', sa.Column('feedback_channel', sa.String(length=64), nullable=True))
    op.add_column('complaints', sa.Column('customer_segment', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_complaints_csi_score'), 'complaints', ['csi_score'], unique=False)
    op.create_index(op.f('ix_complaints_customer_segment'), 'complaints', ['customer_segment'], unique=False)
    op.create_index(op.f('ix_complaints_feedback_channel'), 'complaints', ['feedback_channel'], unique=False)
    op.create_index(op.f('ix_complaints_sentiment'), 'complaints', ['sentiment'], unique=False)
    op.create_index(op.f('ix_complaints_severity'), 'complaints', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_severity'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_sentiment'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_feedback_channel'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_customer_segment'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_csi_score'), table_name='complaints')
    op.drop_column('complaints', 'customer_segment')
    op.drop_column('complaints', 'feedback_channel')
    op.drop_column('complaints', 'severity')
    op.drop_column('complaints', 'sentiment')
    op.drop_column('complaints', 'csi_score')
    # ### end Alembic commands ###
