"""create agent feedback table

Revision ID: fb5fd1b1b99f
Revises: 
Create Date: 2026-06-24 23:41:14.764137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5fd1b1b99f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('answer_source', sa.String(length=32), nullable=True),
    sa.Column('classification_status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_feedback_created_at'), 'agent_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_feedback_feedback_id'), 'agent_feedback', ['feedback_id'], unique=True)
    op.create_index(op.f('ix_agent_feedback_id'), 'agent_feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_feedback_id'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_feedback_id'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_created_at'), table_name='agent_feedback')
    op.drop_table('agent_feedback')
    # ### end Alembic commands ###
